# Project: ÏîÄ¿2
# Makefile created by Dev-C++ 5.10

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = dllmain.o
LINKOBJ  = dllmain.o
LIBS     = -L"E:/software/Dev-Cpp/MinGW64/lib" -L"E:/software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/software/Dev-Cpp/MinGW64/include" -I"E:/software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/software/Dev-Cpp/MinGW64/include" -I"E:/software/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/software/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = test_dll.dll
CXXFLAGS = $(CXXINCS) -lwsock32 -DBUILDING_DLL=1
CFLAGS   = $(INCS) -lwsock32 -DBUILDING_DLL=1
RM       = rm.exe -f
DEF      = libtest_dll.def
STATIC   = libtest_dll.a

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN) $(DEF) $(STATIC)

$(BIN): $(LINKOBJ)
	$(CC) -shared $(LINKOBJ) -o $(BIN) $(LIBS) -Wl,--output-def,$(DEF),--out-implib,$(STATIC),--add-stdcall-alias

dllmain.o: dllmain.c
	$(CC) -c dllmain.c -o dllmain.o $(CFLAGS)
